#!/usr/bin/env bash

HISTFILE="$HOME/.zsh_history" 
sed -r 's/^:\W[0-9]*:0;(\w*)\W*.*$/\1/g' <"$HISTFILE" | \
	awk '{CMD[$1]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | \
	sort -nr | nl | head -n20
