#!/usr/bin/env bash
#----------------------------------------------------
# Author:       Max "keks" Fischer
#
# License:      Beerware
#----------------------------------------------------
# Update automagic all local AUR packages
#----------------------------------------------------
# NOTE:
# Using cower
# TODO:
# Make it work!

# Print string arg. in appropriate error style formating on stdout
error() { echo -e "\e[1;31m$1\e[0;39;49m"; }


fetch_answer() {
	while true; do
		read -p "$1" answer
		answer=$(echo "$answer" | tr 'A-Z' 'a-z')
		if [[ -z $answer || $answer = "y" ]]; then
			return 0;
		elif [[ $answer = "n" ]]; then
			return 1;
		fi
	done
}


if [[ ! -x "/usr/bin/cower" ]]; then
	echo "Dependency cower is missing"
	exit 1
fi

for i in $(pacman -Qm | awk '{ print $1 }'); do
	VERSION=$(cower -i --format %v $i 2> /dev/null)
	CURVERSION=$(pacman -Q $i | awk '{ print $2 }')
	if [[ -z $VERSION ]]; then
		error "error: $i not found in AUR"
		continue
	elif [[ $CURVERSION != $VERSION ]]; then
		if [[ $(fetch_answer "update $i? [Y/n]: ") -eq 0 ]]; then
			echo update!
		fi
	fi
done
exit 0
